services:
  - type: web
    name: busca-de-vagas-api
    env: python
    buildCommand: |
      python --version  # 🔹 Exibe a versão do Python no log
      pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir
      pip install jobspy --no-cache-dir
    startCommand: "bash start.sh"
    plan: free
    envVars:
      - key: REDIS_URL
        value: "redis://seu-redis-url-aqui"
